# # This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
# version: 2.1

# # Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# # See: https://circleci.com/docs/2.0/orb-intro/
# orbs:
#   node: circleci/node@4.7

# # Invoke jobs via workflows
# # See: https://circleci.com/docs/2.0/configuration-reference/#workflows
# workflows:
#   sample: # This is the name of the workflow, feel free to change it to better match your workflow.
#     # Inside the workflow, you define the jobs you want to run.
#     jobs:
#       - node/test:
#           # This is the node version to use for the `cimg/node` tag
#           # Relevant tags can be found on the CircleCI Developer Hub
#           # https://circleci.com/developer/images/image/cimg/node
#           version: '16.10'
#           # If you are using yarn, change the line below from "npm" to "yarn"
#           pkg-manager: npm

version: 2.1

orbs:
  aws-ecs: circleci/aws-ecs@3.2.0
jobs:
  deploy:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - add_ssh_keys:
          fingerprints:
            - "c1:c2:91:02:f8:5c:e1:f4:39:c5:b4:3f:3b:fe:12:45"
      - run:
          name: Install Circlecli
          command: |
            sudo snap install docker circleci
            sudo snap connect circleci:docker docker

      - run:
          name: Deploy to EC2
          command: |
            ssh  -o StrictHostKeyChecking=no  ec2-user@ec2-43-206-230-212.ap-northeast-1.compute.amazonaws.com
      - run: mkdir hello-circle

workflows:
  deploy:
    jobs:
      - deploy
# c1:c2:91:02:f8:5c:e1:f4:39:c5:b4:3f:3b:fe:12:45

