# # CircleCI configuration file
# version: 2.1

# jobs:
#   # Job one with a unique name
#   say_hello:
#     docker:
#       - image: cimg/base:2022.05

#     steps:
#       - run: echo "Say hello to YAML!"
#   # Job two with a unique name
#   say_goodbye:
#     docker:
#       - image: cimg/base:2022.05

#     steps:
#       - run: echo "Say goodbye to YAML!"

# workflows:
#   # Name of workflow
#   hello_and_goodbye:
#     # List of jobs that will run
#     jobs:
#       - say_hello
#       - say_goodbye

version: 2.1

jobs:
  print-hello:
    docker:
      - image: cimg/base:2022.05
    steps:
      - checkout
      - run:
        command: |
          echo 'hello world'

workflows:
  version: 2
  print:
    jobs:
      - print-hello
